services:
  - type: web
    name: sgd-events
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sgd_events.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
